SCHEDULER_STARTED = SCHEDULER_START = 1
SCHEDULER_SHUTDOWN = 2
SCHEDULER_PAUSED = 4
SCHEDULER_RESUMED = 8
EXECUTOR_ADDED = 16
EXECUTOR_REMOVED = 32
STORE_ADDED = 64
STORE_REMOVED = 128
ALL_JOBS_REMOVED = 256
JOB_ADDED = 512
JOB_REMOVED = 1024
JOB_MODIFIED = 2048
JOB_EXECUTED = 4096
JOB_ERROR = 8192
JOB_MISSED = 16384
JOB_SUBMITTED = 32768
JOB_MAX_INSTANCES = 65536

ALL_EVENTS = (
    SCHEDULER_STARTED
    | SCHEDULER_START
    | SCHEDULER_SHUTDOWN
    | SCHEDULER_PAUSED
    | SCHEDULER_RESUMED
    | EXECUTOR_ADDED
    | EXECUTOR_REMOVED
    | STORE_ADDED
    | STORE_REMOVED
    | ALL_JOBS_REMOVED
    | JOB_ADDED
    | JOB_REMOVED
    | JOB_MODIFIED
    | JOB_EXECUTED
    | JOB_ERROR
    | JOB_MISSED
    | JOB_SUBMITTED
    | JOB_MAX_INSTANCES
)
