SCHEDULER_STARTED = SCHEDULER_START = 1
SCHEDULER_SHUTDOWN = 2
SCHEDULER_PAUSED = 4
SCHEDULER_RESUMED = 8
EXECUTOR_ADDED = 16
EXECUTOR_REMOVED = 32
STORE_ADDED = 64
STORE_REMOVED = 128
ALL_TASKS_REMOVED = 256
TASK_ADDED = 512
TASK_REMOVED = 1024
TASK_MODIFIED = 2048
TASK_EXECUTED = 4096
TASK_ERROR = 8192
TASK_MISSED = 16384
TASK_SUBMITTED = 32768
TASK_MAX_INSTANCES = 65536

ALL_EVENTS = (
    SCHEDULER_STARTED
    | SCHEDULER_START
    | SCHEDULER_SHUTDOWN
    | SCHEDULER_PAUSED
    | SCHEDULER_RESUMED
    | EXECUTOR_ADDED
    | EXECUTOR_REMOVED
    | STORE_ADDED
    | STORE_REMOVED
    | ALL_TASKS_REMOVED
    | TASK_ADDED
    | TASK_REMOVED
    | TASK_MODIFIED
    | TASK_EXECUTED
    | TASK_ERROR
    | TASK_MISSED
    | TASK_SUBMITTED
    | TASK_MAX_INSTANCES
)
