---
name: CodSpeed Benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v6"
      - uses: "actions/setup-python@v6"
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install -e ".[testing]"
          pip install pytest-codspeed==4.3.0
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: pytest tests/test_benchmarks.py --codspeed
